[package]
name = "aws-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.18.2"
aws-config = "0.12.0"
lambda_runtime = "0.5.1"
serde_json = "1.0.81"