## From - https://github.com/awslabs/aws-lambda-rust-runtime
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    AutoPublishAlias: live
    MemorySize: 256
    Timeout: 30
Resources:
  AwsRustTest:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/basic/

Outputs:
  FunctionName:
    Value: !Ref AwsRustTest
    Description: Name of the Lambda function